services:
  employees-mysql:
    image: nihadtp/mysql:v1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=employees
      - MYSQL_USER=nihadtp
      - MYSQL_PASSWORD=password

  dbt-mysql:
    image: nihadtp/dbt_employees:v1
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/mysql_employee:/usr/app
      - ${PWD}/profiles.yml:/root/.dbt/profiles.yml
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - employees-mysql