services:
  employees-mysql:
    image: nihadtp/mysql:v2
    entrypoint: ["docker-entrypoint.sh"]
    command: ["mysqld"]
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=employees
      - MYSQL_USER=nihadtp
      - MYSQL_PASSWORD=password

  dbt-mysql:
    image: nihadtp/dbt_employees:v2
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/mysql_employee:/usr/app
      - ${PWD}/profiles.yml:/root/.dbt/profiles.yml
    entrypoint: ["/usr/entrypoint.sh"]
    depends_on:
      - employees-mysql