mysql_employee:
  target: dev
  outputs:
    dev:
      type: mysql
      server: employees-mysql
      port: 3306
      schema: datamart
      username: root
      password: password
      ssl_disabled: True