
version: 2

sources:
  - name: landing
    schema: employees
    tables:
      - name: employees
        identifier: employees
        description: "A table of employees"
        columns:
          - name: first_name
            description: "First Name of the Employee"
            tests:
              - string_not_empty
          - name: gender
            description: "Gnerder of the Employee"
            tests:
              - accepted_values: 
                  values: ['M', 'F']
          
      - name: dept_emp
        identifier: dept_emp
        description: "A table of departments epmloyees relationship"
      - name: departments
        identifier: departments
        description: "A table of department information"
      - name: titles
        identifier: titles
        description: "A table of employee titles"
      - name: salaries
        identifier: salaries
        description: "A table of employee salaries"


models:
  - name: dept_emp_dist
    description: "NUmber of employees per department"
    columns:
      - name: Department
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

      - name: dept_no
        description: "The primary key for this table"
        tests:
          - relationship: 
              to: ref('landing', 'departments')
              field: dept_no
         



